[project]
name = "skg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=3.2.0",
]

[dependency-groups]
dev = [
    "ruff>=0.9.6",
]
